prl = int(input('Digite um valor de 1 a 1000:'))
print('-' * 13)
print('{} x {:2} = {}'.format(prl,1, prl*1))
print('{} x {:2} = {}'.format(prl,2, prl*2))
print('{} x {:2} = {}'.format(prl,3, prl*3))
print('{} x {:2} = {}'.format(prl,4, prl*4))
print('{} x {:2} = {}'.format(prl,5, prl*5))
print('{} x {:2} = {}'.format(prl,6, prl*6))
print('{} x {:2} = {}'.format(prl,7, prl*7))
print('{} x {:2} = {}'.format(prl,8, prl*8))
print('{} x {:2} = {}'.format(prl,9, prl*9))
print('{} x {:2} = {}'.format(prl,10, prl*10))
print('-' * 13)